#!/usr/bin/env python3
"""
deloypl

   deploypl UNIX script

@author: K.Edeline
"""
import sys
from deployer.deploypl import PLDeployer

pld = PLDeployer() 
cmd = pld.args.cmd
cmd_switch = {
   'start'   : pld.start,
   'stop'    : pld.stop,
   'restart' : pld.restart,
   'status'  : pld.status,
}

if cmd in cmd_switch:
   retval = cmd_switch[cmd]()
   sys.exit(retval)
else:
   sys.stdout.write("{} command not found\n".format(cmd))
   sys.exit(2)

